/*
 * This file is generated by jOOQ.
 */
package roppa.apibackend.database;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import roppa.apibackend.database.tables.Watchlist;
import roppa.apibackend.database.tables.records.WatchlistRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>roppa</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<WatchlistRecord> KEY_WATCHLIST_PRIMARY = UniqueKeys0.KEY_WATCHLIST_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<WatchlistRecord> KEY_WATCHLIST_PRIMARY = Internal.createUniqueKey(Watchlist.WATCHLIST, "KEY_watchlist_PRIMARY", new TableField[] { Watchlist.WATCHLIST.COMPANY_NAME }, true);
    }
}
