/*
 * This file is generated by jOOQ.
 */
package roppa.apibackend.database;


import roppa.apibackend.database.tables.Watchlist;


/**
 * Convenience access to all tables in roppa
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>roppa.watchlist</code>.
     */
    public static final Watchlist WATCHLIST = Watchlist.WATCHLIST;
}
