/*
 * This file is generated by jOOQ.
 */
package roppa.apibackend.database.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import roppa.apibackend.database.Keys;
import roppa.apibackend.database.Roppa;
import roppa.apibackend.database.tables.records.WatchlistRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Watchlist extends TableImpl<WatchlistRecord> {

    private static final long serialVersionUID = -1377766630;

    /**
     * The reference instance of <code>roppa.watchlist</code>
     */
    public static final Watchlist WATCHLIST = new Watchlist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WatchlistRecord> getRecordType() {
        return WatchlistRecord.class;
    }

    /**
     * The column <code>roppa.watchlist.company_name</code>.
     */
    public final TableField<WatchlistRecord, String> COMPANY_NAME = createField(DSL.name("company_name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>roppa.watchlist.per</code>.
     */
    public final TableField<WatchlistRecord, Integer> PER = createField(DSL.name("per"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>roppa.watchlist</code> table reference
     */
    public Watchlist() {
        this(DSL.name("watchlist"), null);
    }

    /**
     * Create an aliased <code>roppa.watchlist</code> table reference
     */
    public Watchlist(String alias) {
        this(DSL.name(alias), WATCHLIST);
    }

    /**
     * Create an aliased <code>roppa.watchlist</code> table reference
     */
    public Watchlist(Name alias) {
        this(alias, WATCHLIST);
    }

    private Watchlist(Name alias, Table<WatchlistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Watchlist(Name alias, Table<WatchlistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Watchlist(Table<O> child, ForeignKey<O, WatchlistRecord> key) {
        super(child, key, WATCHLIST);
    }

    @Override
    public Schema getSchema() {
        return Roppa.ROPPA;
    }

    @Override
    public UniqueKey<WatchlistRecord> getPrimaryKey() {
        return Keys.KEY_WATCHLIST_PRIMARY;
    }

    @Override
    public List<UniqueKey<WatchlistRecord>> getKeys() {
        return Arrays.<UniqueKey<WatchlistRecord>>asList(Keys.KEY_WATCHLIST_PRIMARY);
    }

    @Override
    public Watchlist as(String alias) {
        return new Watchlist(DSL.name(alias), this);
    }

    @Override
    public Watchlist as(Name alias) {
        return new Watchlist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Watchlist rename(String name) {
        return new Watchlist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Watchlist rename(Name name) {
        return new Watchlist(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
